# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_kuwo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 624)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 20, 681, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:2px groove gray;border-radius:10px;padding:2px 4px")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(60, 110, 681, 411))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(1, font)
        self.treeWidget.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(2, font)
        self.treeWidget.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(3, font)
        self.treeWidget.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(4, font)
        self.treeWidget.header().setDefaultSectionSize(130)
        self.btnSel_ALL = QtWidgets.QPushButton(self.centralwidget)
        self.btnSel_ALL.setGeometry(QtCore.QRect(210, 80, 75, 23))
        self.btnSel_ALL.setObjectName("btnSel_ALL")
        self.btnSel_None = QtWidgets.QPushButton(self.centralwidget)
        self.btnSel_None.setGeometry(QtCore.QRect(340, 80, 75, 23))
        self.btnSel_None.setObjectName("btnSel_None")
        self.btnSel_Invs = QtWidgets.QPushButton(self.centralwidget)
        self.btnSel_Invs.setGeometry(QtCore.QRect(470, 80, 75, 23))
        self.btnSel_Invs.setObjectName("btnSel_Invs")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 530, 681, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actSong_Download = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Image/icon/download.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSong_Download.setIcon(icon)
        self.actSong_Download.setObjectName("actSong_Download")
        self.actSong_Search = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Image/icon/search.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSong_Search.setIcon(icon1)
        self.actSong_Search.setObjectName("actSong_Search")
        self.toolBar.addAction(self.actSong_Download)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "酷我音乐下载器"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入歌手名/歌曲名"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "序号"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "歌曲"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "歌手"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "专辑"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "时长"))
        self.btnSel_ALL.setText(_translate("MainWindow", "全选"))
        self.btnSel_None.setText(_translate("MainWindow", "全不选"))
        self.btnSel_Invs.setText(_translate("MainWindow", "反选"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actSong_Download.setText(_translate("MainWindow", "下载歌曲"))
        self.actSong_Download.setToolTip(_translate("MainWindow", "下载歌曲"))
        self.actSong_Search.setText(_translate("MainWindow", "搜索"))
        self.actSong_Search.setToolTip(_translate("MainWindow", "搜索"))
