# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 0, 631, 401))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSetHeader = QtWidgets.QPushButton(self.groupBox)
        self.btnSetHeader.setObjectName("btnSetHeader")
        self.gridLayout.addWidget(self.btnSetHeader, 0, 0, 1, 2)
        self.btnSetRows = QtWidgets.QPushButton(self.groupBox)
        self.btnSetRows.setObjectName("btnSetRows")
        self.gridLayout.addWidget(self.btnSetRows, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.btnIniData = QtWidgets.QPushButton(self.groupBox)
        self.btnIniData.setObjectName("btnIniData")
        self.gridLayout.addWidget(self.btnIniData, 2, 0, 1, 2)
        self.btnInsertRow = QtWidgets.QPushButton(self.groupBox)
        self.btnInsertRow.setObjectName("btnInsertRow")
        self.gridLayout.addWidget(self.btnInsertRow, 3, 0, 1, 1)
        self.btnAppendRow = QtWidgets.QPushButton(self.groupBox)
        self.btnAppendRow.setObjectName("btnAppendRow")
        self.gridLayout.addWidget(self.btnAppendRow, 3, 1, 1, 1)
        self.btnDelCurRow = QtWidgets.QPushButton(self.groupBox)
        self.btnDelCurRow.setObjectName("btnDelCurRow")
        self.gridLayout.addWidget(self.btnDelCurRow, 4, 0, 1, 1)
        self.btnClearContents = QtWidgets.QPushButton(self.groupBox)
        self.btnClearContents.setObjectName("btnClearContents")
        self.gridLayout.addWidget(self.btnClearContents, 4, 1, 1, 1)
        self.btnAutoHeight = QtWidgets.QPushButton(self.groupBox)
        self.btnAutoHeight.setObjectName("btnAutoHeight")
        self.gridLayout.addWidget(self.btnAutoHeight, 5, 0, 1, 1)
        self.btnAutoWidth = QtWidgets.QPushButton(self.groupBox)
        self.btnAutoWidth.setObjectName("btnAutoWidth")
        self.gridLayout.addWidget(self.btnAutoWidth, 5, 1, 1, 1)
        self.btnReadToText = QtWidgets.QPushButton(self.groupBox)
        self.btnReadToText.setObjectName("btnReadToText")
        self.gridLayout.addWidget(self.btnReadToText, 6, 0, 1, 2)
        self.chkBoxEditable = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxEditable.setChecked(True)
        self.chkBoxEditable.setObjectName("chkBoxEditable")
        self.gridLayout.addWidget(self.chkBoxEditable, 7, 0, 1, 1)
        self.chkBoxRowColor = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxRowColor.setChecked(True)
        self.chkBoxRowColor.setObjectName("chkBoxRowColor")
        self.gridLayout.addWidget(self.chkBoxRowColor, 7, 1, 1, 1)
        self.chkBoxHeaderH = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxHeaderH.setChecked(True)
        self.chkBoxHeaderH.setObjectName("chkBoxHeaderH")
        self.gridLayout.addWidget(self.chkBoxHeaderH, 8, 0, 1, 1)
        self.chkBoxHeaderV = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxHeaderV.setChecked(True)
        self.chkBoxHeaderV.setObjectName("chkBoxHeaderV")
        self.gridLayout.addWidget(self.chkBoxHeaderV, 8, 1, 1, 1)
        self.radioSelectRow = QtWidgets.QRadioButton(self.groupBox)
        self.radioSelectRow.setObjectName("radioSelectRow")
        self.gridLayout.addWidget(self.radioSelectRow, 9, 0, 1, 1)
        self.radioSelectItem = QtWidgets.QRadioButton(self.groupBox)
        self.radioSelectItem.setChecked(True)
        self.radioSelectItem.setObjectName("radioSelectItem")
        self.gridLayout.addWidget(self.radioSelectItem, 9, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setAutoFillBackground(False)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("alternate-background-color: rgb(255, 170, 255);")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSetHeader.setText(_translate("MainWindow", "设置表头"))
        self.btnSetRows.setText(_translate("MainWindow", "设置行数"))
        self.btnIniData.setText(_translate("MainWindow", "初始化表格数据"))
        self.btnInsertRow.setText(_translate("MainWindow", "插入行"))
        self.btnAppendRow.setText(_translate("MainWindow", "添加行"))
        self.btnDelCurRow.setText(_translate("MainWindow", "删除当前行"))
        self.btnClearContents.setText(_translate("MainWindow", "清空表格内容"))
        self.btnAutoHeight.setText(_translate("MainWindow", "自动调节行高"))
        self.btnAutoWidth.setText(_translate("MainWindow", "自动调节列宽"))
        self.btnReadToText.setText(_translate("MainWindow", "读取表格内容到文本"))
        self.chkBoxEditable.setText(_translate("MainWindow", "表格可编辑"))
        self.chkBoxRowColor.setText(_translate("MainWindow", "间隔行底色"))
        self.chkBoxHeaderH.setText(_translate("MainWindow", "显示行表头"))
        self.chkBoxHeaderV.setText(_translate("MainWindow", "显示列表头"))
        self.radioSelectRow.setText(_translate("MainWindow", "行选择"))
        self.radioSelectItem.setText(_translate("MainWindow", "单元格选择"))
