# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TableWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 0, 771, 551))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.btnSetHeader = QtWidgets.QPushButton(self.groupBox)
        self.btnSetHeader.setObjectName("btnSetHeader")
        self.gridLayout.addWidget(self.btnSetHeader, 0, 0, 1, 2)
        self.btnSetRows = QtWidgets.QPushButton(self.groupBox)
        self.btnSetRows.setObjectName("btnSetRows")
        self.gridLayout.addWidget(self.btnSetRows, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.btnIniData = QtWidgets.QPushButton(self.groupBox)
        self.btnIniData.setObjectName("btnIniData")
        self.gridLayout.addWidget(self.btnIniData, 2, 0, 1, 2)
        self.btnInsertRow = QtWidgets.QPushButton(self.groupBox)
        self.btnInsertRow.setObjectName("btnInsertRow")
        self.gridLayout.addWidget(self.btnInsertRow, 3, 0, 1, 1)
        self.btnAppendRow = QtWidgets.QPushButton(self.groupBox)
        self.btnAppendRow.setObjectName("btnAppendRow")
        self.gridLayout.addWidget(self.btnAppendRow, 3, 1, 1, 1)
        self.btnDelCurRow = QtWidgets.QPushButton(self.groupBox)
        self.btnDelCurRow.setObjectName("btnDelCurRow")
        self.gridLayout.addWidget(self.btnDelCurRow, 4, 0, 1, 1)
        self.btnClearContents = QtWidgets.QPushButton(self.groupBox)
        self.btnClearContents.setObjectName("btnClearContents")
        self.gridLayout.addWidget(self.btnClearContents, 4, 1, 1, 1)
        self.btnAutoHeight = QtWidgets.QPushButton(self.groupBox)
        self.btnAutoHeight.setObjectName("btnAutoHeight")
        self.gridLayout.addWidget(self.btnAutoHeight, 5, 0, 1, 1)
        self.btnAutoWidth = QtWidgets.QPushButton(self.groupBox)
        self.btnAutoWidth.setObjectName("btnAutoWidth")
        self.gridLayout.addWidget(self.btnAutoWidth, 5, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 6, 0, 1, 2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 7, 0, 1, 1)
        self.chkBoxRowColor = QtWidgets.QCheckBox(self.groupBox)
        self.chkBoxRowColor.setObjectName("chkBoxRowColor")
        self.gridLayout.addWidget(self.chkBoxRowColor, 7, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 8, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 8, 1, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 9, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 9, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.splitter)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSetHeader.setText(_translate("MainWindow", "设置表头"))
        self.btnSetRows.setText(_translate("MainWindow", "设置行数"))
        self.btnIniData.setText(_translate("MainWindow", "初始化表格数据"))
        self.btnInsertRow.setText(_translate("MainWindow", "插入行"))
        self.btnAppendRow.setText(_translate("MainWindow", "添加行"))
        self.btnDelCurRow.setText(_translate("MainWindow", "删除当前行"))
        self.btnClearContents.setText(_translate("MainWindow", "清空表格内容"))
        self.btnAutoHeight.setText(_translate("MainWindow", "自动调节行高"))
        self.btnAutoWidth.setText(_translate("MainWindow", "自动调节列宽"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.chkBoxRowColor.setText(_translate("MainWindow", "间隔行底色"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton"))
