# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TreeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 721, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabPicture = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.LabPicture.setText("")
        self.LabPicture.setAlignment(QtCore.Qt.AlignCenter)
        self.LabPicture.setObjectName("LabPicture")
        self.horizontalLayout_2.addWidget(self.LabPicture)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1003, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "节点")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.treeWidget.header().setDefaultSectionSize(150)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actTree_AddFolder = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/icon/AddFolder.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actTree_AddFolder.setIcon(icon)
        self.actTree_AddFolder.setObjectName("actTree_AddFolder")
        self.actTree_AddFiles = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/icon/AddFiles.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actTree_AddFiles.setIcon(icon1)
        self.actTree_AddFiles.setObjectName("actTree_AddFiles")
        self.actZoomIn = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/icon/ZoomIn.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomIn.setIcon(icon2)
        self.actZoomIn.setObjectName("actZoomIn")
        self.actZoomOut = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/icon/ZoomOut.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomOut.setIcon(icon3)
        self.actZoomOut.setObjectName("actZoomOut")
        self.actZoomRealSize = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/icon/ZoomRealSize.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomRealSize.setIcon(icon4)
        self.actZoomRealSize.setObjectName("actZoomRealSize")
        self.actTree_DeleteItem = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/icon/delete.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actTree_DeleteItem.setIcon(icon5)
        self.actTree_DeleteItem.setObjectName("actTree_DeleteItem")
        self.actZoomFitH = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("image/icon/height.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomFitH.setIcon(icon6)
        self.actZoomFitH.setObjectName("actZoomFitH")
        self.actZoomFitW = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("image/icon/width.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actZoomFitW.setIcon(icon7)
        self.actZoomFitW.setObjectName("actZoomFitW")
        self.actTree_ScanItems = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("image/icon/scanitem.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actTree_ScanItems.setIcon(icon8)
        self.actTree_ScanItems.setObjectName("actTree_ScanItems")
        self.actDockFloat = QtWidgets.QAction(MainWindow)
        self.actDockFloat.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("image/icon/dockfloat.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDockFloat.setIcon(icon9)
        self.actDockFloat.setObjectName("actDockFloat")
        self.actDockVisible = QtWidgets.QAction(MainWindow)
        self.actDockVisible.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("image/icon/dockvisible.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDockVisible.setIcon(icon10)
        self.actDockVisible.setObjectName("actDockVisible")
        self.actClose = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("image/icon/quit.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actClose.setIcon(icon11)
        self.actClose.setObjectName("actClose")
        self.menu.addAction(self.actTree_AddFolder)
        self.menu.addAction(self.actTree_AddFiles)
        self.menu.addAction(self.actTree_DeleteItem)
        self.menu.addAction(self.actTree_ScanItems)
        self.menu.addSeparator()
        self.menu.addAction(self.actClose)
        self.menu_2.addAction(self.actZoomIn)
        self.menu_2.addAction(self.actZoomOut)
        self.menu_2.addAction(self.actZoomRealSize)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.actZoomFitH)
        self.menu_2.addAction(self.actZoomFitW)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.toolBar.addAction(self.actTree_AddFolder)
        self.toolBar.addAction(self.actTree_AddFiles)
        self.toolBar.addAction(self.actTree_DeleteItem)
        self.toolBar.addAction(self.actTree_ScanItems)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actZoomIn)
        self.toolBar.addAction(self.actZoomOut)
        self.toolBar.addAction(self.actZoomRealSize)
        self.toolBar.addAction(self.actZoomFitW)
        self.toolBar.addAction(self.actZoomFitH)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actDockFloat)
        self.toolBar.addAction(self.actDockVisible)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actClose)

        self.retranslateUi(MainWindow)
        self.actClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "目录树"))
        self.menu_2.setTitle(_translate("MainWindow", "视图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "图片目录树"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "节点类型"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "图片文件"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "分组节点"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "图片节点"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "分组2"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "图片2"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.actTree_AddFolder.setText(_translate("MainWindow", "添加目录..."))
        self.actTree_AddFolder.setToolTip(_translate("MainWindow", "添加目录"))
        self.actTree_AddFolder.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actTree_AddFiles.setText(_translate("MainWindow", "添加文件..."))
        self.actTree_AddFiles.setToolTip(_translate("MainWindow", "添加文件"))
        self.actTree_AddFiles.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actZoomIn.setText(_translate("MainWindow", "放大"))
        self.actZoomIn.setToolTip(_translate("MainWindow", "放大图片"))
        self.actZoomIn.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actZoomOut.setText(_translate("MainWindow", "缩小"))
        self.actZoomOut.setToolTip(_translate("MainWindow", "缩小图片"))
        self.actZoomOut.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actZoomRealSize.setText(_translate("MainWindow", "实际大小"))
        self.actZoomRealSize.setToolTip(_translate("MainWindow", "图片实际大小显示"))
        self.actTree_DeleteItem.setText(_translate("MainWindow", "删除节点"))
        self.actTree_DeleteItem.setToolTip(_translate("MainWindow", "删除节点"))
        self.actZoomFitH.setText(_translate("MainWindow", "适合高度"))
        self.actZoomFitH.setToolTip(_translate("MainWindow", "适合高度"))
        self.actZoomFitH.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actZoomFitW.setText(_translate("MainWindow", "适合宽度"))
        self.actZoomFitW.setToolTip(_translate("MainWindow", "适合宽度"))
        self.actZoomFitW.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actTree_ScanItems.setText(_translate("MainWindow", "遍历节点"))
        self.actTree_ScanItems.setToolTip(_translate("MainWindow", "遍历节点"))
        self.actDockFloat.setText(_translate("MainWindow", "窗体浮动"))
        self.actDockFloat.setToolTip(_translate("MainWindow", "窗体浮动"))
        self.actDockVisible.setText(_translate("MainWindow", "窗体可见"))
        self.actDockVisible.setToolTip(_translate("MainWindow", "窗体可见"))
        self.actClose.setText(_translate("MainWindow", "退出"))
        self.actClose.setToolTip(_translate("MainWindow", "退出"))
